export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  DASHBOARD: '/dashboard',
  PROJECT: '/project-management',
  PROJECT_DETAILS: '/project-details/',
  PROJECT_CREATE: '/project-management/create',
  PROJECT_EDIT: '/project-management/edit/',
  CLIENTS: '/clients',
  LEADS: '/leads',
  INBOX: '/inbox',
  ANALYTICS: '/analytics',
  SETTINGS: '/settings',
} as const;
